### ISSUE TITLE
Switching Workspaces turns off add-on

### ISSUE THREAD

**Issue by j-conrad** [nutti/Screencast-Keys#20]
**System Information**
  
* OS: Windows 10
* Blender version: 2.82.7
* Add-on version: 3.1.0

**Expected behavior**  
Screencast Keys add-on should stay toggled on (or off) in all Workspaces

**Description about the bug**  
If you're in, say, the Modeling workspace and turn on Screencast Keys, then switch to another workspace mode like 'UV Editing', Screencast Keys stops displaying your key/mouse presses even though the add-on has the checkbox on. Toggling it off/on fixes it until you switch to another workspace.

**Comment by nutti** [comment]
@j-conrad 

What's your 'origin' option?
If this option is 'Region' or 'Area', Screencast Keys will not display at new workspace because new workspace has different area or region from the original workspace.
If you want to continue displaying while switching workspace, you need to execute 'Set Origin' or use option 'Window'.

Anyway, this is a specification of this add-on not a bug.
If you have any issues about this specification, feel free to contact us.
Thanks.
