### ISSUE TITLE
Startup File and New Files v.3.2.0

### ISSUE THREAD

**Issue by L-Travieso** [nutti/Screencast-Keys#25]
**System Information**
  
* OS: Windows 10 / 64bit
* Blender version: 2.83.1
* Add-on version: 3.2.0

**Expected behavior**  

- Screencast Keys will remain functional after creating a new file (e.g. File > New > General).
- Screencast Keys will remain enabled after enabling it, saving the startup file (File > Defaults > Save Startup File), and restarting Blender.

**Description about the bug**  

- After Screencast Keys is enabled, it will continue to function normally until a new file is made. After a new file is made (e.g. File > New > General), ScreencastKeys will remain enabled, but it's won't display the keys. You can disable it and enable it again to make it work.
- After Screencast Keys is enabled and the Startup file is saved (File > Default > Save Startup File), it will not be enabled when Blender is restarted.

**Screenshots/Files** [Optional]  

**Additional comments** [Optional]

**Comment by nutti** [comment]
@L-Travieso 

Thanks.
But I think this comes from Blender limitation for modal operation.
Do you have any add-on which overcomes this issue?
If you tell me about it, I'm able to fix this issue.

In #14, I resolved this issue to switch off Screencast Key instead.
I think this is a method we can do against this issue.

**Comment by L-Travieso** [comment]
idk I'm new to this. isn't it a question of that checkbox being checked as the default state so that when blender loads it loads as active with it?

**Comment by nutti** [comment]
@L-Travieso 

Maybe this issue is more complicated.
Screencast Key is executed when checkbox is just checked, and move to modal state after that.
If we restart blender or load new blend file, modal state will be off.
So, we need to re-check checkbox everytime after restarting blender or loading blend file.

**Comment by nutti** [comment]
From technical reasons, I could not come over this limitation from add-on level.
The checkbox is activated by the running state of Screencast Keys.
If we creating new file or restarting Blender, the Screencast Keys will be stopped and the checkbox will also be deactivated.

I think we need fixing Blender itself if we realize this feature.
Because of above reasons, I will close this issue for now.

**Comment by CheeryLee** [comment]
I have some thoughts in this topic about features you've described: https://github.com/nutti/Screencast-Keys/issues/63
