### ISSUE TITLE
auto start or shortcut key 

### ISSUE THREAD

**Issue by gurlaldeepsingh** [nutti/Screencast-Keys#28]
**Description about the feature**  
can we please have an auto-start(enable) function with a blender startup.
or maybe just shortcut key to enable the addon so we don't have to Go-to the tab to enable it
because I can't manually set shortcut key in the add on.

**Are you willing to contribute about this feature. (No I can't I know nothing about coding)**

**Comment by nutti** [comment]
@gurlaldeepsingh 

> auto-start(enable) function with a blender startup

We could not realize this feature because of technical reasons described at #25 .
If you know other add-ons which realize this, could you tell me.

> shortcut key to enable the addon

You can enable/disable by `Shift + Alt + C`.
I noticed there is no documentation about this shortcut key.
I will add it to the tutorial document.
Thanks.

**Comment by gurlaldeepsingh** [comment]
thank you got it 
and again for the amazing addon.

**Comment by nutti** [comment]
Thanks.

The document has already merged.
So, I will close this issue.
