### ISSUE TITLE
Some actions are not identified

### ISSUE THREAD

**Issue by Almaz** [nutti/Screencast-Keys#6]
**System Information**
* OS: Linux Mint 18.3 Cinnamon 64-bit
* Blender version: 2.80.72
* Add-on version: 3.0.0

**Expected behavior**  
*If I move some vertices 1 meter along the X-axis, I press G, X, 1, expecting all these actions to be displayed.*

**Description about the bug**  
*Indicator only shows G, ignoring the other presses.*

**Comment by nutti** [comment]
This feature is a restriction of original one.

https://developer.blender.org/T37865

Some solution is considered to this feature in Blender 2.79, but it breaks now in Blender 2.8.
I will wait until Blender 2.8 is stable, but I can't guarantee this bug will be fixed.

**Comment by nutti** [comment]
This issue is now resolved.
But this feature uses a hack to get events aggressively, so you need to use it carefully.
You can use this feature by switching on `Get Event Aggressively`.

<img width="491" alt="image_6" src="https://user-images.githubusercontent.com/1463952/80196148-ef1aa900-8657-11ea-9c43-5600156dce28.png">
`

**Comment by 3diuk** [comment]
still not working for me even with get event aggresivley.  For example if I press G to move and then press Z to limit movement to the z axis, the letter z isn't displayed by screencast keys.

**Comment by 3diuk** [comment]
ignore that, I was using last night version, but just noticed you've released another version 4 hours ago.  Now it work.  Thanks for sharing.
