### ISSUE TITLE
Autosave stops working when screencast keys is on

### ISSUE THREAD

**Issue by Evgen0040** [nutti/Screencast-Keys#83]
**System Information**
  
* OS: Windows 10
* Blender version: 3.0 steam
* Add-on version: 3.6.0

**Expected behavior**  
Blender make new autosave accordingly to autosave settings

**Description about the bug**  
When add-on is enabled in n-menu blender not creating new autosave file, after disabling screencast keys from n-menu new autosave file appears immediately

**Comment by nutti** [comment]
In the modal mode, auto saving is disabled from Blender's specification.
But I will try to tackle this issue with some ideas.

**Comment by mac4kent** [comment]
Check YouTube I made to show you. https://youtu.be/0IAvdEJrBQs

**Comment by mac4kent** [comment]
I hope you understand about auto save on Preferences or manual click (Save Pref) button https://youtu.be/gv75teq1chY
about Push the N key same thing

**Comment by Mets3D** [comment]
I suspect this won't be fixable unless it's fixed on Blender's side. In the meantime, I'd maybe add a warning with red text that pops up underneath the checkbox when it's enabled, to inform the user that autosave is disabled. AFAIK this has been an issue since at least 2.76, and I've seen a lot of users, including myself, my colleagues, and this guy: https://developer.blender.org/T95171 lose work because of it.

**Comment by nutti** [comment]
@Mets3D 

Yes, I have already known this issue.
So, I'm trying to call `bpy.ops.wm.save_as_mainfile` operator in modal method per several seconds.
This is not complete solution, but we could imitate the blender's behavior for auto saving.
Any comments are welcomed.

**Comment by nutti** [comment]
This issue is now solved.
If the custom auto save feature, enable **Auto Save** option.
However, be careful to enable this option because this hacks the internal structure of Blender.
So this option is experimental option same as Get Event Aggressively option.

![issue_83](https://user-images.githubusercontent.com/1463952/158008392-9d0bee64-e3fa-425c-892b-9040f0114ef0.png)

**Comment by mac4kent** [comment]
GOOD Blender 3.1.0 is release right now I let you know.

**Comment by mac4kent** [comment]
Preferences I did check box turn on Auto save not work after push the 'N' key setting.
